services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
      POSTGRES_DB: traveldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://travel:travel@db:5432/traveldb

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  jenkins_home:
