services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel
      POSTGRES_DB: traveldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://travel:travel@db:5432/traveldb

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  prometheus:
    build:
      context: ./monitoring
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
    - grafana_data:/var/lib/grafana    
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:  
