pipeline {
agent any


stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Docker Images') {
        steps {
            dir('travel-devops') {
                sh 'docker compose down'
                sh 'docker compose up -d --build'
            }
        }
    }

    stage('Deploy') {
        steps {
            dir('travel-devops') {
                sh 'docker compose up -d'
            }
        }
    }

}


}

