pipeline {
agent any


stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Deploy') {
        steps {
            sh '''
            cd /home/mircea/ProiectDev/travel-devops
            docker compose down
            docker compose up -d --build
            '''
        }
    }

}


}


